[package]
name = "tailwag"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tailwag_application = { version = "0.1.0", path = "application" }
tailwag_macros = { version = "0.1.0", path = "macros" }
tailwag_orm = { version = "0.1.0", path = "orm" }
tailwag_utils = { version = "0.1.0", path = "utils" }

[features]
default = ["macros"]
macros = []
